services:
  willow:
    container_name: willow-be
    image: meelunae/willow-be
    restart: always
    build: ./backend # Ensure backend has a separate folder
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  frontend:
    container_name: willow-fe
    image: meelunae/willow-fe
    build: ./frontend # Ensure frontend has a separate folder
    ports:
      - "3001:3000"
    depends_on:
      - willow
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000 # Backend API URL for frontend

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
