services:
  willow:
    container_name: willow-be
    image: meelunae/willow-be
    restart: always
    build: ./backend
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    container_name: willow-fe
    image: meelunae/willow-fe
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    depends_on:
      - willow
    env_file:
      - ./frontend/.env

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT:-27018}:27017"
